### ISSUE TITLE
Handle revised archived processing

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw-designer#28]
**This is for remote project imports only**

In WorkflowAssetsRest.importGitAssets, the new GitVcs service should be used for mdw 6.0.07+.  The new archiving will automaticatlly be taken care of in that case.

This is more about displaying in-flight instances from ASSET_REF.

**Comment by donaldoakes** [comment]
Use this branch for creating in-flight records in asset_ref:
https://github.com/CenturyLinkCloud/mdw/tree/issue_207_Don_Jack

**Comment by naveena-bellamkonda** [comment]
This depends on issue# 11
