### ISSUE TITLE
Substititution in file when sending a notice 

### ISSUE THREAD

**Issue by ab59451** [CenturyLinkCloud/mdw-designer#5]
When sending tokens in notify event using file command. Substitutions are not happening. Workaround it to copy the content in test script itself. Or to use the "post http" syntax for sending the event.

**Comment by naveena-bellamkonda** [comment]
Rightnow, only masterRequestId value is getting resolved in the message. processInstanceId and activityInstanceId are being replaced as server side variable. Same is fixed in case of file content.
