### ISSUE TITLE
Remove all unauthenticated service access in mdw6

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw-designer#53]
This relates to the following MDW issue:
https://github.com/CenturyLinkCloud/mdw/issues/349

Designer should always authenticate for remote project access to these services.  Locally users generally run with -Dmdw.runtime.env=dev, so authentication is not required.  Therefore, most Designer access can use the equivalent proper service that MDWHub also uses.  Some services may need to be disabled for remote projects that don't use mdw auth.

**Comment by naveena-bellamkonda** [comment]
All the service calls are being sent with authentication. will create a separate issue for replacing the old style services for mdw6 remote project.
