### ISSUE TITLE
Import remote Git VCS project does not need deep clone

### ISSUE THREAD

**Issue by ab59451** [CenturyLinkCloud/mdw-designer#7]
For Git VCS remote projects, importing in Designer can take a very long time. Currently we needlessly clone the entire repo history. Explore whether there's an option in JGit to do something similar to the --depth option in git clone.

**Comment by naveena-bellamkonda** [comment]
I think this issue is blocked until JGit has shallow clone capabilities:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=475615
