### ISSUE TITLE
Designer package import issues

### ISSUE THREAD

**Issue by jbrojdeCTL** [CenturyLinkCloud/mdw-designer#77]
When importing 6.1.05 packages that will replace existing 6.0.12 packages, Designer fails giving an IOException about not finding the package.json file (I think in Archive folder). Workaround here is to manually remove Archive folder and existing package directory from file system and re-import.   Should Designer still be trying to archive existing packages into the now gone/defunct Archive directory? 

Also, when doing import package from File, it seems it also triggers a re-import of all existing packages already in project instead of only importing the specified package from File.

**Comment by naveena-bellamkonda** [comment]
The import issue is not reproducible.

Regarding the second part of the issue, it is the subtask message getting displayed along with the main meassge (Import Packages) while taking backup of the  packages. It is not actually importing the existing packages.
