### ISSUE TITLE
Error reports should be sent through a REST service instead of SMTP 

### ISSUE THREAD

**Issue by ab59451** [CenturyLinkCloud/mdw-designer#9]
We need to create a REST service for error reporting. Designer should use this service instead of JavaMail for error reporting. We can make this service generic enough so that in the future it can be used by other clients (like MDWHub).

Or we can just send these through a Slack webhook.

**Comment by donaldoakes** [comment]
We can add a REST service in mdw-central to listen for these reports.

**Comment by donaldoakes** [comment]
REST endpoint is now available on mdw-central at:
https://mdw-central.com/errors

Look at the error reporter in mdw-mobile for an example of how to POST:
https://github.com/CenturyLinkCloud/mdw-mobile/blob/master/android/mdw/mdw/src/main/java/com/centurylink/mdw/mobile/app/Reporter.java
